# ----------------------------------------
# ✅ Hasan Shaikh - Academic Portfolio Site
# Based on academicpages.github.io
# ----------------------------------------

# Basic Site Info
locale          : "en-US"
title           : "Hasan Shaikh"
title_separator : "-"
name            : "Hasan Shaikh"
description     : "Clinical Data Scientist | AI in Oncology Imaging | Radiomics & ML"
url             : "https://hash123shaikh.github.io"   # For user site (hash123shaikh.github.io)
baseurl         : ""                                   # Keep empty for user site
repository      : "hash123shaikh/Hasan_Portfolio"      # Update if your repo name changes


# Author Details
author:
  avatar   : "hasan_profile.jpg"
  name     : "Hasan Shaikh"
  pronouns : "he/him"
  bio      : "Clinical Data Scientist @ CMC Vellore | Radiomics & AI in Oncology Imaging"
  location : "Tamil Nadu, India"
  employer : "Christian Medical College, Vellore"
  uri      : "https://www.cmcvellore.ac.in"
  email    : "hasanshaikh3198@gmail.com"


  # Profiles
  googlescholar : "https://scholar.google.com/citations?user=9jjwZ8cAAAAJ"
  github        : "hash123shaikh"
  linkedin      : "hasann-shaikh"


# Publication Types
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'


# Site Settings
breadcrumbs       : false
future            : true
timezone          : "Asia/Kolkata"
permalink         : "/:categories/:title/"


# Markdown & Syntax Highlighting
markdown          : kramdown
highlighter       : rouge
excerpt_separator : "\n\n"
kramdown:
  input           : GFM
  hard_wrap       : false
  auto_ids        : true
  toc_levels      : 1..6
  entity_output   : as_char


# RSS Feed
atom_feed:
  hide: false


# Collections
collections:
  teaching:
    output   : true
    permalink: /:collection/:path/
  publications:
    output   : true
    permalink: /:collection/:path/
  portfolio:
    output   : true
    permalink: /:collection/:path/
  talks:
    output   : true
    permalink: /:collection/:path/


# Default Layouts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout        : single
      author_profile: true
      read_time     : true
      share         : true
      comments      : false
      related       : true

  - scope:
      path: ""
      type: pages
    values:
      layout        : single
      author_profile: true

  - scope:
      path: ""
      type: teaching
    values:
      layout        : single
      author_profile: true

  - scope:
      path: ""
      type: publications
    values:
      layout        : single
      author_profile: true

  - scope:
      path: ""
      type: portfolio
    values:
      layout        : single
      author_profile: true

  - scope:
      path: ""
      type: talks
    values:
      layout        : talk
      author_profile: true

# Plugins
plugins:
  - jekyll-include-cache     # ← the cache plugin
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# Permalinks
permalink: /:categories/:title/
timezone : Asia/Kolkata

# Folders to Include/Exclude
include:
  - _pages
  - files

exclude:
  - .github
  - node_modules
  - vendor
  - tmp
  - README
  - Gemfile
  - Rakefile
  - Dockerfile
  - package.json*
  - config
  - LICENSE
  - CHANGELOG

keep_files:
  - .git

encoding     : "utf-8"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# Set a skin
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"   # or "air", "mint", "contrast", etc.



